services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: |
      chmod +x entrypoint.sh
    startCommand: |
      ./entrypoint.sh
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: superseguro
      - key: N8N_HOST
        value: https://n8n-tuapp.onrender.com